# Generated by Django 3.2.3 on 2023-09-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20230902_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNo', models.CharField(max_length=11, verbose_name='phone number')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('level', models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], default=1, verbose_name='chocie')),
                ('status', models.SmallIntegerField(choices=[(1, 'occupied'), (2, 'unoccupied')], default=2, verbose_name='status')),
            ],
        ),
    ]
